### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by raxele123** [djravine/idlecombos#12]
Dark Mode please my eyes hurt.

"Use Blacksmith Contracts" please save the amount of contracts you use. By save I mean when you insert a certain champion's ID, the next time you use a blacksmith contract it defaults to that champion. I would like the same to be applied to the amount of contracts.

Hotkeys that send me straight to the "How many Blacksmith Contracts?" For every type of blacksmith contract. Also the choice to change key bindings please.

"Buy Event" and "Open Event" chests that is. Insert the event chest id and buy/open event chests though IdleCombos rather than SoulReaver. Though SoulReaver is just buy not open.

Increase the font size of the "Champ IDs" please. Or maybe it's just me.

Please and thank you. (Reposted from Discussions.)

**Comment by djravine** [comment]
## Dark Mode - MAYBE IN THE FUTURE
Will require a lot more research (may not even be possible).
There is not a simple option to enable the dark theme like UWP as AHK is a Win32 system.
Ideally windows need to rollout implementation for dark mode support for Win32 applications.
I will continue to investigate as I would like this feature also.
I can currently detect if dark mode is enabled in the Windows OS but there is no native support in AHK to change buttons colours.
**LINK:** https://www.autohotkey.com/boards/viewtopic.php?t=94661

## Save Blacksmith Contracts Amount - DONE
Currently it will always default to the total number of contracts of the type selected.
This makes it easy to apply all available contracts to one character.
I will update the code to store the count per Blacksmith Contract type if this value is changed.
It will also check if the last count is larger than the max remaining and populate accordingly.
This stored value will reset after reload/reopen.

## Save Blacksmith Contracts Champ ID - ALREADY DONE
Currently it should auto populate with the last used Champ ID.
Once you have opened contracts for a Champ ID, it is stored and should auto populate the Champ ID the next time.
This stored value will reset after reload/reopen.

## Blacksmith Contracts Hotkeys - DONE
Updated the Blacksmith Contracts hotkeys via the menu:
- Tiny Contracts - **ALT, T, B, T**
- Small Contracts - **ALT, T, B, S**
- Medium Contracts - **ALT, T, B, M**
- Large Contracts - **ALT, T, B, L**
- Huge Contracts - **ALT, T, B, H**

## Open/Buy Chests Hotkeys - DONE
Updated the Open/Buy Chests hotkeys
- Buy Silver -  **ALT, T, C, S**
- Buy Gold -  **ALT, T, C, G**
- Buy Event -  **ALT, T, C, E**
- Open Silver - **ALT, T, C, I**
- Open Gold -  **ALT, T, C, O**
- Open Event - **ALT, T, C, V**

## Change Hotkeys/Key Bindings - POSSIBLE FUTURE
To store edited hotkeys will require a fair amount of work, otherwise they would reset on reload/reopen.
Might look at this in the future.

## Event Chests - POSSIBLE FUTURE
Will investigate

## Font Size - Champ IDs + User Details - DONE
Easy to do, will update.

## Release Progress
Working in **develop** branch and will make a new release in the next day or so...

**Comment by djravine** [comment]
Now in Releases
